### ISSUE TITLE
Update for currently available toolchain?

### ISSUE THREAD

**Issue by twadleigh** [hughski/colorhug2-firmware#1]
Apparently `mplabc18-v3.40-linux-full-installer.run` is no longer available on `microchip.com`. I made some an attempt to install the analogous toolchain that is currently supported, but was ultimately unsuccessful in getting it to build, myself.

**Comment by hughsie** [comment]
Microchip keep doing this, it's not exactly helping. For ColorHug+ I moved to xc8, although that turned into more of a rewrite... is that what you tried to use?

**Comment by twadleigh** [comment]
Yes. Specifically, I installed:
 - `xc8-v1.45-full-install-linux-installer.run` for `mplabc18-v3.40-linux-full-installer.run`;
 - `mla_v2017_03_06_linux_installer.run` for `microchip-libraries-for-applications-v2013-06-15-linux-installer.run`; and
 - `peripheral-libraries-for-pic18-v2.00rc3-linux-installer.run` to pick up the otherwise missing `delays.h` and `i2c.h`.

With some path hacking in `Makefile` and sources I was able to get some things to compile, but then hit:
```
/opt/microchip/xc8/v1.45/bin/mcc18 -I/opt/microchip/xc8/v1.45/include -I/opt/microchip/xc8/v1.45/include/plib -I/opt/microchip/libs-v2017-03-06/framework/usb/inc -p18f46j50 -w3 -nw=3004 usb_descriptors.c -fo usb_descriptors_firmware.o
(924) missing argument to "-O" option
(908) exit status = 1
Makefile:155: recipe for target 'usb_descriptors_firmware.o' failed
make: *** [usb_descriptors_firmware.o] Error 1
```
